env:
  global:
    - CC_TEST_REPORTER_ID=132207e4a4a3bf016e1168855be63b9e14a2a8f9287f58dece5a984750dd5f7a
language: ruby
rvm:
- 2.4.4
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
deploy:
  provider: heroku
  api_key:
    secure: UIIlKqwSm+S9a350OIrJ/lnKeIkS0SCNEigzV3tsDxy+1wbsgZTXPuTLmNDdllENnWD/GCKGdZrC8SgUaocjPN1vWCE9Fm+sq+8uZyIg+Qb+zm3KpZc+1JT2mh40s3SgCOK1b2EJTa2TAQqaQalBSdnkFMEvF7uLbYzjmnb2cDhObTVODwXsH8BZySVB3YSU9HV88TO3ktoz+DmnNsBmOvL/QFlw9BEBznu/0NqtigiVV5CK2FKjLbxYxOs9R+syXzVBwJn1uyCLqUkgH1I3A4esZHEFy8JcWrNgZ/peQTQeTYbRe4htEWWIuJjxXR/E3FMNYRXm5Xdz4baen9s8mruCcLiR3E5zyZWEyqOJHysV0daW13Ta34JQTrELM8EBonLpvQ6r0i0MZJJae1zvuOM/RBPPysNQVoWQPFxWnXLaEGn3n6JukFIxES8+c1u8CzMnH+2t2zZD4hiW9Guy4okQ9+IVqk/oECNgkTMhc9aZn8WgivXNTSVEtRDadBi/scZRE27Lug9qU5RCWC+kTms3bR9n3e5GJqS8XK0RSY1OGCKRpjoTQ4GzX9VcoOD//tM46Dqz76f3qPJN3XsJ9ie2T4NBbgpNf4hSiVcdFkyyfNDlG/BJ0t2LVZVVqGAoCZDFBzujMO8AoPGiP84bnuIVoVMZQMLEA6oa1sWbcuY=
  run: "rake db:migrate"
  app: tdlp4a
  on:
    repo: EleryanYuri/Project-LP4A-TD
